export const FETCH_BEERS = 'beers/FETCH_BEERS'
export const SORT_BY_ABV = 'beers/SORT_BY_ABV'
export const FETCH_BEER_DETAILS = 'beers/FETCH_BEER_DETAILS'
export const FETCH_BEERS_FAILED = 'beers/FETCH_BEERS_FAILED'
export const RESET_STATE = 'beers/RESET_STATE'
